name: CI

on:
  workflow_dispatch:
  push:
    branches: ["production"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name:
        run: docker build -t fedevcoding/classeviva-bot .
      - name: Push to dockerhub
        run: docker push fedevcoding/classeviva-bot:latest
